name: newline-action
description: Automatically fixes files without a final new line in pull requests.
author: Bruno Logerfo

branding:
  icon: file
  color: white

inputs:
  github-token:
    description: The `GITHUB_TOKEN` secret.
    required: true
  config-path:
    description: The optional configuration file path.
    default: .github/newline.yml

runs:
  using: "node16"
  main: "dist/index.js"
